// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5tecQrSPC9ghHGXyx2hJ2XIBc-LKOu0Y',
    appId: '1:960652171424:web:2dd6e27975180a6d6691c5',
    messagingSenderId: '960652171424',
    projectId: 'test-notification-af33b',
    authDomain: 'test-notification-af33b.firebaseapp.com',
    storageBucket: 'test-notification-af33b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB25zWIoOA1YQqZv3z4iph0IAW1dMBFSAs',
    appId: '1:960652171424:android:181a22ae13ef0bf36691c5',
    messagingSenderId: '960652171424',
    projectId: 'test-notification-af33b',
    storageBucket: 'test-notification-af33b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8YjVQeq-ugYlNYFitjeomvFFJziT5C6c',
    appId: '1:960652171424:ios:3fc55f490d920dd46691c5',
    messagingSenderId: '960652171424',
    projectId: 'test-notification-af33b',
    storageBucket: 'test-notification-af33b.firebasestorage.app',
    iosBundleId: 'com.example.trackingAppDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8YjVQeq-ugYlNYFitjeomvFFJziT5C6c',
    appId: '1:960652171424:ios:3fc55f490d920dd46691c5',
    messagingSenderId: '960652171424',
    projectId: 'test-notification-af33b',
    storageBucket: 'test-notification-af33b.firebasestorage.app',
    iosBundleId: 'com.example.trackingAppDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5tecQrSPC9ghHGXyx2hJ2XIBc-LKOu0Y',
    appId: '1:960652171424:web:f7c8bc08ef8ccdc26691c5',
    messagingSenderId: '960652171424',
    projectId: 'test-notification-af33b',
    authDomain: 'test-notification-af33b.firebaseapp.com',
    storageBucket: 'test-notification-af33b.firebasestorage.app',
  );
}
